header_loggedInAs=You are logged in as: {name}
title=FAForever
title_technicalError=Technical Error
login=Login
login_title=FAForever Login
login_welcomeBack=Welcome back, Commander!
login_badCredentials=Username or password was wrong
login_throttled=Too many of your login attempts have failed. Please wait some time before trying to login again.
login_usernameOrEmail=Username or email
login_password=Password
login_loginAction=Log in
login_forgotPassword=Forgot Password
login_registerAccount=Register Account
login_technicalError=We encountered a technical error during login. This mostly occurs if you reloaded a page or sent a request twice. Please restart the login from the beginning.
consent_appRequest=This app would like to:
consent_termsOfService=Terms of Service
consent_privacyStatement=Privacy Statement
consent_authorize=Authorize
consent_deny=Deny
consent_clientLogo=Client logo
steam_faq=For more information on why ownership verification is required click here
steam_reason=In order to play on FAForever, we need to verify that you own a legal copy of Supreme Commander Forged Alliance. You can verify ownership on the website at
verification_title=Game Ownership Verification Missing
oauth2_scope_textMissing=Translation missing! Technical name: ''{0}''
oauth2_scope_openid=Login via OpenID Connect
oauth2_scope_openid_description=Technically required, does not reveal any data
oauth2_scope_offline=Permanent Login
oauth2_scope_offline_description=The client will receive a token that allows to auto login.
oauth2_scope_public_profile=View profile
oauth2_scope_public_profile_description=Sensitive data such as email will not be revealed.
oauth2_scope_write_account_data=Edit account data
oauth2_scope_write_account_data_description=Such as change password or email
oauth2_scope_edit_clan_data=Edit clan data
oauth2_scope_edit_clan_data_description=Such as renaming or inviting players
oauth2_scope_vote=Participate in FAF votes
oauth2_scope_upload_map=Upload maps
oauth2_scope_upload_mod=Upload mods
oauth2_scope_manage_vault=Manage vault
oauth2_scope_manage_vault_description=Such as hide and unrank maps or mods
oauth2_scope_administrative_actions=Perform administrative actions
oauth2_scope_administrative_actions_description=Such as kick, ban, broadcast message, ...
oauth2_scope_read_sensible_userdata=View sensible user data
oauth2_scope_read_sensible_userdata_description=Such as email, steam id, bans, ...
oauth2_scope_upload_avatar=Upload avatars
oauth2_scope_lobby=Play in the game lobby
ban_title=You are banned from FAForever
ban_expiration=Ban expires at:
ban_permanent=Never
ban_reason=Reason:
ban_appeal=You may appeal your ban by emailing moderation@faforever.com
