faf:
  environment: ${FAF_ENVIRONMENT}
  real-ip-header: ${REAL_IP_HEADER:X-Real-Ip}
  hydra-base-url: ${HYDRA_BASE_ADMIN_URL:http://localhost:4445}
  account:
    password-reset-url: ${PASSWORD_RESET_URL:`https://faforever.com/account/password/reset`}
    register-account-url: ${REGISTER_ACCOUNT_URL:`https://faforever.com/account/register`}
    account-link-url: ${ACCOUNT_LINK_URL:`https://www.faforever.com/account/link`}
    registration:
      activation-url-format: ${ACTIVATION_URL_FORMAT:http://localhost:8080/register/activate?token=%s}
      subject: ${REGISTRATION_EMAIL_SUBJECT:FAF user registration}
      activation-mail-template-path: ${ACCOUNT_ACTIVATION_MAIL_TEMPLATE_PATH:/config/mail/account-activation.html}
      welcome-subject: ${WELCOME_MAIL_SUBJECT:Welcome to FAF}
      welcome-mail-template-path: ${WELCOME_MAIL_TEMPLATE_PATH:/config/mail/welcome-to-faf.html}
      terms-of-service-url: ${FAF_TERMS_OF_SERVICE:https://faforever.com/tos}
      privacy-statement-url: ${FAF_PRIVACY_STATEMENT:https://faforever.com/privacy}
      rules-url: ${FAF_RULES:https://faforever.com/rules}
    password-reset:
      password-reset-url-format: ${PASSWORD_RESET_URL_FORMAT:http://localhost:8080/account/password/confirmReset?token=%s}
      subject: ${PASSWORD_RESET_EMAIL_SUBJECT:FAF password reset}
      mail-template-path: ${PASSWORD_RESET_MAIL_TEMPLATE_PATH:/config/mail/password-reset.html}
    username:
      minimum-days-between-username-change: ${MIN_DAYS_BETWEEN_NAME_CHANGE:30}
      username-reservation-time-in-months: ${NAME_RESERVATION_MONTHS:6}
  recaptcha:
    enabled: ${RECAPTCHA_ENABLED:true}
    secret: ${RECAPTCHA_SECRET:6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe}
    site-key: ${RECAPTCHA_SITE_KEY:6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI}
  jwt:
    secret: ${JWT_SECRET:banana}
  lobby:
    secret: ${LOBBY_SECRET:banana}
    access-uri: ${LOBBY_URL:ws://localhost:8003}
    access-param: ${LOBBY_PARAM:verify}
  irc:
    secret: ${IRC_SECRET:banana}
    token-ttl: ${IRC_TOKEN_TTL:300}

mailjet:
  api-key: ${MAILJET_API_KEY}
  api-secret: ${MAILJET_API_SECRET}

security:
  failed-login-account-threshold: ${FAILED_LOGIN_ACCOUNT_THRESHOLD:5}
  failed-login-attempt-threshold: ${FAILED_LOGIN_ATTEMPT_THRESHOLD:10}
  failed-login-throttling-minutes: ${FAILED_LOGIN_THROTTLING_MINUTES:5}
  failed-login-days-to-check: ${FAILED_LOGIN_DAYS_TO_CHECK:1}

quarkus:
  log:
    level: INFO
  rest-client:
    faf-ory-hydra:
      url: ${HYDRA_BASE_ADMIN_URL:http://localhost:4445}
    recaptcha:
      url: https://www.google.com/recaptcha/api
  mailer:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:0}
    username: ${MAIL_USERNAME:mailer}
    password: ${MAIL_PASSWORD:banana}
    start-tls: OPTIONAL
    ssl: true
    login: REQUIRED
    from: ${EMAIL_FROM_ADDRESS:admin@faforever.com}
    mock: ${MOCK_EMAIL:true}
  devservices:
    enabled: false
  datasource:
    db-kind: mariadb
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:banana}
    jdbc:
      url: ${DB_URL:jdbc:mariadb://localhost:3306/faf?ssl=false}
  application:
    name: faf-user-service
  management:
    enabled: true

"%dev":
  quarkus:
    live-reload:
      instrumentation: true
    http:
      cors:
        origins: "/.*/"
    mailer:
      mock: true
    log:
      category:
        "com.faforever":
          level: DEBUG
  faf:
    environment: ${FAF_ENVIRONMENT:dev}
    account:
      registration:
        activation-mail-template-path: ${ACCOUNT_ACTIVATION_MAIL_TEMPLATE_PATH:../../../../src/main/mjml/dummy/test-account-activation.html}
        welcome-mail-template-path: ${WELCOME_MAIL_TEMPLATE_PATH:../../../../src/main/mjml/dummy/test-welcome-to-faf.html}
      password-reset:
        mail-template-path: ${PASSWORD_RESET_MAIL_TEMPLATE_PATH:../../../../src/main/mjml/dummy/test-password-reset.html}
    irc:
      fixed:
        users:
          test-user: banana

mp:
  jwt:
    verify:
      issuer: ${HYDRA_TOKEN_ISSUER:http://faf-ory-hydra:4444/}
      key-format: JWKS
      publickey:
        location: ${HYDRA_JWKS_URL:http://localhost:4444/.well-known/jwks.json}