security:
  failedLoginAccountThreshold: ${FAILED_LOGIN_ACCOUNT_THRESHOLD:5}
  failedLoginAttemptThreshold: ${FAILED_LOGIN_ATTEMPT_THRESHOLD:10}
  failedLoginThrottlingMinutes: ${FAILED_LOGIN_THROTTLING_MINUTES:5}

hydra:
  baseUrl: http://localhost:4445

logging:
  level:
    com.faforever: debug

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/faf?ssl=false
    username: faf-java-api
    password: banana
  messages:
    basename: i18n/messages
