/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty
import io.quarkus.runtime.annotations.RegisterForReflection

/**
 *
 * @param grantAccessTokenAudience
 * @param grantScope
 * @param handledAt
 * @param remember Remember, if set to true, tells ORY Hydra to remember this consent authorization and reuse it if the same client asks the same user for the same, or a subset of, scope.
 * @param rememberFor RememberFor sets how long the consent authorization should be remembered for in seconds. If set to `0`, the authorization will be remembered indefinitely.
 * @param session
 */

@RegisterForReflection
data class AcceptConsentRequest(
    @JsonProperty("grant_access_token_audience")
    val grantAccessTokenAudience: kotlin.collections.List<kotlin.String>? = null,
    @JsonProperty("grant_scope")
    val grantScope: kotlin.collections.List<kotlin.String>? = null,
    @JsonProperty("handled_at")
    val handledAt: java.time.OffsetDateTime? = null,
    /* Remember, if set to true, tells ORY Hydra to remember this consent authorization and reuse it if the same client asks the same user for the same, or a subset of, scope. */
    @JsonProperty("remember")
    val remember: kotlin.Boolean? = null,
    /* RememberFor sets how long the consent authorization should be remembered for in seconds. If set to `0`, the authorization will be remembered indefinitely. */
    @JsonProperty("remember_for")
    val rememberFor: kotlin.Long? = null,
    @JsonProperty("session")
    val session: ConsentRequestSession? = null,
)
