/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * ContainerWaitOKBodyError container waiting error, if any
 * @param message Details of an error
 */

data class ContainerWaitOKBodyError(
    /* Details of an error */
    @field:JsonProperty("Message")
    val message: kotlin.String? = null
)
