/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Error
 *
 * @param error Error
 * @param errorDebug Error Debug Information  Only available in dev mode.
 * @param errorDescription Error Description
 * @param errorHint Error Hint  Helps the user identify the error cause.
 * @param statusCode HTTP Status Code
 */

data class ErrorOAuth2(

    /* Error */
    @get:JsonProperty("error")
    val error: kotlin.String? = null,

    /* Error Debug Information  Only available in dev mode. */
    @get:JsonProperty("error_debug")
    val errorDebug: kotlin.String? = null,

    /* Error Description */
    @get:JsonProperty("error_description")
    val errorDescription: kotlin.String? = null,

    /* Error Hint  Helps the user identify the error cause. */
    @get:JsonProperty("error_hint")
    val errorHint: kotlin.String? = null,

    /* HTTP Status Code */
    @get:JsonProperty("status_code")
    val statusCode: kotlin.Long? = null,

)
