/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 * @param errors Errors contains a list of errors that caused the not ready status.
 */

data class HealthNotReadyStatus(
    /* Errors contains a list of errors that caused the not ready status. */
    @field:JsonProperty("errors")
    val errors: kotlin.collections.Map<kotlin.String, kotlin.String>? = null
)
