/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * It is important that this model object is named JSONWebKey for \"swagger generate spec\" to generate only on definition of a JSONWebKey.
 * @param alg The \"alg\" (algorithm) parameter identifies the algorithm intended for use with the key.  The values used should either be registered in the IANA \"JSON Web Signature and Encryption Algorithms\" registry established by [JWA] or be a value that contains a Collision- Resistant Name.
 * @param kid The \"kid\" (key ID) parameter is used to match a specific key.  This is used, for instance, to choose among a set of keys within a JWK Set during key rollover.  The structure of the \"kid\" value is unspecified.  When \"kid\" values are used within a JWK Set, different keys within the JWK Set SHOULD use distinct \"kid\" values.  (One example in which different keys might use the same \"kid\" value is if they have different \"kty\" (key type) values but are considered to be equivalent alternatives by the application using them.)  The \"kid\" value is a case-sensitive string.
 * @param kty The \"kty\" (key type) parameter identifies the cryptographic algorithm family used with the key, such as \"RSA\" or \"EC\". \"kty\" values should either be registered in the IANA \"JSON Web Key Types\" registry established by [JWA] or be a value that contains a Collision- Resistant Name.  The \"kty\" value is a case-sensitive string.
 * @param use Use (\"public key use\") identifies the intended use of the public key. The \"use\" parameter is employed to indicate whether a public key is used for encrypting data or verifying the signature on data. Values are commonly \"sig\" (signature) or \"enc\" (encryption).
 * @param crv
 * @param d
 * @param dp
 * @param dq
 * @param e
 * @param k
 * @param n
 * @param p
 * @param q
 * @param qi
 * @param x
 * @param x5c The \"x5c\" (X.509 certificate chain) parameter contains a chain of one or more PKIX certificates [RFC5280].  The certificate chain is represented as a JSON array of certificate value strings.  Each string in the array is a base64-encoded (Section 4 of [RFC4648] -- not base64url-encoded) DER [ITU.X6901994] PKIX certificate value. The PKIX certificate containing the key value MUST be the first certificate.
 * @param y
 */

data class JSONWebKey(
    /* The \"alg\" (algorithm) parameter identifies the algorithm intended for use with the key.  The values used should either be registered in the IANA \"JSON Web Signature and Encryption Algorithms\" registry established by [JWA] or be a value that contains a Collision- Resistant Name. */
    @field:JsonProperty("alg")
    val alg: kotlin.String,
    /* The \"kid\" (key ID) parameter is used to match a specific key.  This is used, for instance, to choose among a set of keys within a JWK Set during key rollover.  The structure of the \"kid\" value is unspecified.  When \"kid\" values are used within a JWK Set, different keys within the JWK Set SHOULD use distinct \"kid\" values.  (One example in which different keys might use the same \"kid\" value is if they have different \"kty\" (key type) values but are considered to be equivalent alternatives by the application using them.)  The \"kid\" value is a case-sensitive string. */
    @field:JsonProperty("kid")
    val kid: kotlin.String,
    /* The \"kty\" (key type) parameter identifies the cryptographic algorithm family used with the key, such as \"RSA\" or \"EC\". \"kty\" values should either be registered in the IANA \"JSON Web Key Types\" registry established by [JWA] or be a value that contains a Collision- Resistant Name.  The \"kty\" value is a case-sensitive string. */
    @field:JsonProperty("kty")
    val kty: kotlin.String,
    /* Use (\"public key use\") identifies the intended use of the public key. The \"use\" parameter is employed to indicate whether a public key is used for encrypting data or verifying the signature on data. Values are commonly \"sig\" (signature) or \"enc\" (encryption). */
    @field:JsonProperty("use")
    val use: kotlin.String,
    @field:JsonProperty("crv")
    val crv: kotlin.String? = null,
    @field:JsonProperty("d")
    val d: kotlin.String? = null,
    @field:JsonProperty("dp")
    val dp: kotlin.String? = null,
    @field:JsonProperty("dq")
    val dq: kotlin.String? = null,
    @field:JsonProperty("e")
    val e: kotlin.String? = null,
    @field:JsonProperty("k")
    val k: kotlin.String? = null,
    @field:JsonProperty("n")
    val n: kotlin.String? = null,
    @field:JsonProperty("p")
    val p: kotlin.String? = null,
    @field:JsonProperty("q")
    val q: kotlin.String? = null,
    @field:JsonProperty("qi")
    val qi: kotlin.String? = null,
    @field:JsonProperty("x")
    val x: kotlin.String? = null,
    /* The \"x5c\" (X.509 certificate chain) parameter contains a chain of one or more PKIX certificates [RFC5280].  The certificate chain is represented as a JSON array of certificate value strings.  Each string in the array is a base64-encoded (Section 4 of [RFC4648] -- not base64url-encoded) DER [ITU.X690.1994] PKIX certificate value. The PKIX certificate containing the key value MUST be the first certificate. */
    @field:JsonProperty("x5c")
    val x5c: kotlin.collections.List<kotlin.String>? = null,
    @field:JsonProperty("y")
    val y: kotlin.String? = null
)
