/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 * @param challenge Challenge is the identifier (\"logout challenge\") of the logout authentication request. It is used to identify the session.
 * @param requestUrl RequestURL is the original Logout URL requested.
 * @param rpInitiated RPInitiated is set to true if the request was initiated by a Relying Party (RP), also known as an OAuth 2.0 Client.
 * @param sid SessionID is the login session ID that was requested to log out.
 * @param subject Subject is the user for whom the logout was request.
 */

data class LogoutRequest(
    /* Challenge is the identifier (\"logout challenge\") of the logout authentication request. It is used to identify the session. */
    @field:JsonProperty("challenge")
    val challenge: kotlin.String? = null,
    /* RequestURL is the original Logout URL requested. */
    @field:JsonProperty("request_url")
    val requestUrl: kotlin.String? = null,
    /* RPInitiated is set to true if the request was initiated by a Relying Party (RP), also known as an OAuth 2.0 Client. */
    @field:JsonProperty("rp_initiated")
    val rpInitiated: kotlin.Boolean? = null,
    /* SessionID is the login session ID that was requested to log out. */
    @field:JsonProperty("sid")
    val sid: kotlin.String? = null,
    /* Subject is the user for whom the logout was request. */
    @field:JsonProperty("subject")
    val subject: kotlin.String? = null
)
