/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param accessToken
 * @param authorizeCode
 * @param idToken
 * @param parContext
 * @param refreshToken
 */

data class OAuth2ConsentSessionExpiresAt(

    @JsonProperty("access_token")
    val accessToken: java.time.OffsetDateTime? = null,

    @JsonProperty("authorize_code")
    val authorizeCode: java.time.OffsetDateTime? = null,

    @JsonProperty("id_token")
    val idToken: java.time.OffsetDateTime? = null,

    @JsonProperty("par_context")
    val parContext: java.time.OffsetDateTime? = null,

    @JsonProperty("refresh_token")
    val refreshToken: java.time.OffsetDateTime? = null,

)
