/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The Access Token Response
 * @param accessToken
 * @param expiresIn
 * @param idToken
 * @param refreshToken
 * @param scope
 * @param tokenType
 */

data class Oauth2TokenResponse(
    @field:JsonProperty("access_token")
    val accessToken: kotlin.String? = null,
    @field:JsonProperty("expires_in")
    val expiresIn: kotlin.Long? = null,
    @field:JsonProperty("id_token")
    val idToken: kotlin.String? = null,
    @field:JsonProperty("refresh_token")
    val refreshToken: kotlin.String? = null,
    @field:JsonProperty("scope")
    val scope: kotlin.String? = null,
    @field:JsonProperty("token_type")
    val tokenType: kotlin.String? = null
)
