/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A completed OAuth 2.0 Consent Session.
 *
 * @param consentRequest
 * @param consentRequestId ConsentRequestID is the identifier of the consent request that initiated this consent session.
 * @param context
 * @param grantAccessTokenAudience
 * @param grantScope
 * @param handledAt
 * @param remember Remember Consent  Remember, if set to true, tells ORY Hydra to remember this consent authorization and reuse it if the same client asks the same user for the same, or a subset of, scope.
 * @param rememberFor Remember Consent For  RememberFor sets how long the consent authorization should be remembered for in seconds. If set to `0`, the authorization will be remembered indefinitely.
 * @param session
 */

data class OAuth2ConsentSession(

    @get:JsonProperty("consent_request")
    val consentRequest: OAuth2ConsentRequest? = null,

    /* ConsentRequestID is the identifier of the consent request that initiated this consent session. */
    @get:JsonProperty("consent_request_id")
    val consentRequestId: kotlin.String? = null,

    @get:JsonProperty("context")
    val context: kotlin.Any? = null,

    @get:JsonProperty("grant_access_token_audience")
    val grantAccessTokenAudience: kotlin.collections.List<kotlin.String>? = null,

    @get:JsonProperty("grant_scope")
    val grantScope: kotlin.collections.List<kotlin.String>? = null,

    @get:JsonProperty("handled_at")
    val handledAt: java.time.OffsetDateTime? = null,

    /* Remember Consent  Remember, if set to true, tells ORY Hydra to remember this consent authorization and reuse it if the same client asks the same user for the same, or a subset of, scope. */
    @get:JsonProperty("remember")
    val remember: kotlin.Boolean? = null,

    /* Remember Consent For  RememberFor sets how long the consent authorization should be remembered for in seconds. If set to `0`, the authorization will be remembered indefinitely. */
    @get:JsonProperty("remember_for")
    val rememberFor: kotlin.Long? = null,

    @get:JsonProperty("session")
    val session: AcceptOAuth2ConsentRequestSession? = null,

)
