/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A JSONPatch document as defined by RFC 6902
 * @param op The operation to be performed
 * @param path A JSON-pointer
 * @param from A JSON-pointer
 * @param value The value to be used within the operations
 */

data class PatchDocument(
    /* The operation to be performed */
    @field:JsonProperty("op")
    val op: kotlin.String,
    /* A JSON-pointer */
    @field:JsonProperty("path")
    val path: kotlin.String,
    /* A JSON-pointer */
    @field:JsonProperty("from")
    val from: kotlin.String? = null,
    /* The value to be used within the operations */
    @field:JsonProperty("value")
    val value: kotlin.Any? = null
)
