/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * PluginConfigRootfs plugin config rootfs
 * @param diffIds diff ids
 * @param type type
 */

data class PluginConfigRootfs(
    /* diff ids */
    @field:JsonProperty("diff_ids")
    val diffIds: kotlin.collections.List<kotlin.String>? = null,
    /* type */
    @field:JsonProperty("type")
    val type: kotlin.String? = null
)
