/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * PluginEnv plugin env
 * @param description description
 * @param name name
 * @param settable settable
 * @param value value
 */

data class PluginEnv(
    /* description */
    @field:JsonProperty("Description")
    val description: kotlin.String,
    /* name */
    @field:JsonProperty("Name")
    val name: kotlin.String,
    /* settable */
    @field:JsonProperty("Settable")
    val settable: kotlin.collections.List<kotlin.String>,
    /* value */
    @field:JsonProperty("Value")
    val value: kotlin.String
)
