/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * PluginConfigInterface The interface between Docker and the plugin
 * @param socket socket
 * @param types types
 */

data class PluginConfigInterface(
    /* socket */
    @field:JsonProperty("Socket")
    val socket: kotlin.String,
    /* types */
    @field:JsonProperty("Types")
    val types: kotlin.collections.List<PluginInterfaceType>
)
