/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * PluginDevice plugin device
 * @param description description
 * @param name name
 * @param path path
 * @param settable settable
 */

data class PluginDevice(
    /* description */
    @field:JsonProperty("Description")
    val description: kotlin.String,
    /* name */
    @field:JsonProperty("Name")
    val name: kotlin.String,
    /* path */
    @field:JsonProperty("Path")
    val path: kotlin.String,
    /* settable */
    @field:JsonProperty("Settable")
    val settable: kotlin.collections.List<kotlin.String>
)
