/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * PluginConfigUser plugin config user
 * @param GID g ID
 * @param UID UID
 */

data class PluginConfigUser(
    /* g ID */
    @field:JsonProperty("GID")
    val GID: kotlin.Int? = null,
    /* UID */
    @field:JsonProperty("UID")
    val UID: kotlin.Int? = null
)
