/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 * @param args args
 * @param devices devices
 * @param env env
 * @param mounts mounts
 */

data class PluginSettings(
    /* args */
    @field:JsonProperty("Args")
    val args: kotlin.collections.List<kotlin.String>,
    /* devices */
    @field:JsonProperty("Devices")
    val devices: kotlin.collections.List<PluginDevice>,
    /* env */
    @field:JsonProperty("Env")
    val env: kotlin.collections.List<kotlin.String>,
    /* mounts */
    @field:JsonProperty("Mounts")
    val mounts: kotlin.collections.List<PluginMount>
)
