/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * PluginInterfaceType plugin interface type
 * @param capability capability
 * @param prefix prefix
 * @param version version
 */

data class PluginInterfaceType(
    /* capability */
    @field:JsonProperty("Capability")
    val capability: kotlin.String,
    /* prefix */
    @field:JsonProperty("Prefix")
    val prefix: kotlin.String,
    /* version */
    @field:JsonProperty("Version")
    val version: kotlin.String
)
