/**
* ORY Hydra
* Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
*
* The version of the OpenAPI document: latest
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package sh.ory.hydra.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * It includes links to several endpoints (e.g. /oauth2/token) and exposes information on supported signature algorithms among others.
 * @param authorizationEndpoint URL of the OP's OAuth 2.0 Authorization Endpoint.
 * @param idTokenSigningAlgValuesSupported JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP for the ID Token to encode the Claims in a JWT.
 * @param issuer URL using the https scheme with no query or fragment component that the OP asserts as its IssuerURL Identifier. If IssuerURL discovery is supported , this value MUST be identical to the issuer value returned by WebFinger. This also MUST be identical to the iss Claim value in ID Tokens issued from this IssuerURL.
 * @param jwksUri URL of the OP's JSON Web Key Set [JWK] document. This contains the signing key(s) the RP uses to validate signatures from the OP. The JWK Set MAY also contain the Server's encryption key(s), which are used by RPs to encrypt requests to the Server. When both signing and encryption keys are made available, a use (Key Use) parameter value is REQUIRED for all keys in the referenced JWK Set to indicate each key's intended usage. Although some algorithms allow the same key to be used for both signatures and encryption, doing so is NOT RECOMMENDED, as it is less secure. The JWK x5c parameter MAY be used to provide X.509 representations of keys provided. When used, the bare key values MUST still be present and MUST match those in the certificate.
 * @param responseTypesSupported JSON array containing a list of the OAuth 2.0 response_type values that this OP supports. Dynamic OpenID Providers MUST support the code, id_token, and the token id_token Response Type values.
 * @param subjectTypesSupported JSON array containing a list of the Subject Identifier types that this OP supports. Valid types include pairwise and public.
 * @param tokenEndpoint URL of the OP's OAuth 2.0 Token Endpoint
 * @param backchannelLogoutSessionSupported Boolean value specifying whether the OP can pass a sid (session ID) Claim in the Logout Token to identify the RP session with the OP. If supported, the sid Claim is also included in ID Tokens issued by the OP
 * @param backchannelLogoutSupported Boolean value specifying whether the OP supports back-channel logout, with true indicating support.
 * @param claimsParameterSupported Boolean value specifying whether the OP supports use of the claims parameter, with true indicating support.
 * @param claimsSupported JSON array containing a list of the Claim Names of the Claims that the OpenID Provider MAY be able to supply values for. Note that for privacy or other reasons, this might not be an exhaustive list.
 * @param endSessionEndpoint URL at the OP to which an RP can perform a redirect to request that the End-User be logged out at the OP.
 * @param frontchannelLogoutSessionSupported Boolean value specifying whether the OP can pass iss (issuer) and sid (session ID) query parameters to identify the RP session with the OP when the frontchannel_logout_uri is used. If supported, the sid Claim is also included in ID Tokens issued by the OP.
 * @param frontchannelLogoutSupported Boolean value specifying whether the OP supports HTTP-based logout, with true indicating support.
 * @param grantTypesSupported JSON array containing a list of the OAuth 2.0 Grant Type values that this OP supports.
 * @param registrationEndpoint URL of the OP's Dynamic Client Registration Endpoint.
 * @param requestParameterSupported Boolean value specifying whether the OP supports use of the request parameter, with true indicating support.
 * @param requestUriParameterSupported Boolean value specifying whether the OP supports use of the request_uri parameter, with true indicating support.
 * @param requireRequestUriRegistration Boolean value specifying whether the OP requires any request_uri values used to be pre-registered using the request_uris registration parameter.
 * @param responseModesSupported JSON array containing a list of the OAuth 2.0 response_mode values that this OP supports.
 * @param revocationEndpoint URL of the authorization server's OAuth 2.0 revocation endpoint.
 * @param scopesSupported SON array containing a list of the OAuth 2.0 [RFC6749] scope values that this server supports. The server MUST support the openid scope value. Servers MAY choose not to advertise some supported scope values even when this parameter is used
 * @param tokenEndpointAuthMethodsSupported JSON array containing a list of Client Authentication methods supported by this Token Endpoint. The options are client_secret_post, client_secret_basic, client_secret_jwt, and private_key_jwt, as described in Section 9 of OpenID Connect Core 1.0
 * @param userinfoEndpoint URL of the OP's UserInfo Endpoint.
 * @param userinfoSigningAlgValuesSupported JSON array containing a list of the JWS [JWS] signing algorithms (alg values) [JWA] supported by the UserInfo Endpoint to encode the Claims in a JWT [JWT].
 */

data class WellKnown(
    /* URL of the OP's OAuth 2.0 Authorization Endpoint. */
    @field:JsonProperty("authorization_endpoint")
    val authorizationEndpoint: kotlin.String,
    /* JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP for the ID Token to encode the Claims in a JWT. */
    @field:JsonProperty("id_token_signing_alg_values_supported")
    val idTokenSigningAlgValuesSupported: kotlin.collections.List<kotlin.String>,
    /* URL using the https scheme with no query or fragment component that the OP asserts as its IssuerURL Identifier. If IssuerURL discovery is supported , this value MUST be identical to the issuer value returned by WebFinger. This also MUST be identical to the iss Claim value in ID Tokens issued from this IssuerURL. */
    @field:JsonProperty("issuer")
    val issuer: kotlin.String,
    /* URL of the OP's JSON Web Key Set [JWK] document. This contains the signing key(s) the RP uses to validate signatures from the OP. The JWK Set MAY also contain the Server's encryption key(s), which are used by RPs to encrypt requests to the Server. When both signing and encryption keys are made available, a use (Key Use) parameter value is REQUIRED for all keys in the referenced JWK Set to indicate each key's intended usage. Although some algorithms allow the same key to be used for both signatures and encryption, doing so is NOT RECOMMENDED, as it is less secure. The JWK x5c parameter MAY be used to provide X.509 representations of keys provided. When used, the bare key values MUST still be present and MUST match those in the certificate. */
    @field:JsonProperty("jwks_uri")
    val jwksUri: kotlin.String,
    /* JSON array containing a list of the OAuth 2.0 response_type values that this OP supports. Dynamic OpenID Providers MUST support the code, id_token, and the token id_token Response Type values. */
    @field:JsonProperty("response_types_supported")
    val responseTypesSupported: kotlin.collections.List<kotlin.String>,
    /* JSON array containing a list of the Subject Identifier types that this OP supports. Valid types include pairwise and public. */
    @field:JsonProperty("subject_types_supported")
    val subjectTypesSupported: kotlin.collections.List<kotlin.String>,
    /* URL of the OP's OAuth 2.0 Token Endpoint */
    @field:JsonProperty("token_endpoint")
    val tokenEndpoint: kotlin.String,
    /* Boolean value specifying whether the OP can pass a sid (session ID) Claim in the Logout Token to identify the RP session with the OP. If supported, the sid Claim is also included in ID Tokens issued by the OP */
    @field:JsonProperty("backchannel_logout_session_supported")
    val backchannelLogoutSessionSupported: kotlin.Boolean? = null,
    /* Boolean value specifying whether the OP supports back-channel logout, with true indicating support. */
    @field:JsonProperty("backchannel_logout_supported")
    val backchannelLogoutSupported: kotlin.Boolean? = null,
    /* Boolean value specifying whether the OP supports use of the claims parameter, with true indicating support. */
    @field:JsonProperty("claims_parameter_supported")
    val claimsParameterSupported: kotlin.Boolean? = null,
    /* JSON array containing a list of the Claim Names of the Claims that the OpenID Provider MAY be able to supply values for. Note that for privacy or other reasons, this might not be an exhaustive list. */
    @field:JsonProperty("claims_supported")
    val claimsSupported: kotlin.collections.List<kotlin.String>? = null,
    /* URL at the OP to which an RP can perform a redirect to request that the End-User be logged out at the OP. */
    @field:JsonProperty("end_session_endpoint")
    val endSessionEndpoint: kotlin.String? = null,
    /* Boolean value specifying whether the OP can pass iss (issuer) and sid (session ID) query parameters to identify the RP session with the OP when the frontchannel_logout_uri is used. If supported, the sid Claim is also included in ID Tokens issued by the OP. */
    @field:JsonProperty("frontchannel_logout_session_supported")
    val frontchannelLogoutSessionSupported: kotlin.Boolean? = null,
    /* Boolean value specifying whether the OP supports HTTP-based logout, with true indicating support. */
    @field:JsonProperty("frontchannel_logout_supported")
    val frontchannelLogoutSupported: kotlin.Boolean? = null,
    /* JSON array containing a list of the OAuth 2.0 Grant Type values that this OP supports. */
    @field:JsonProperty("grant_types_supported")
    val grantTypesSupported: kotlin.collections.List<kotlin.String>? = null,
    /* URL of the OP's Dynamic Client Registration Endpoint. */
    @field:JsonProperty("registration_endpoint")
    val registrationEndpoint: kotlin.String? = null,
    /* Boolean value specifying whether the OP supports use of the request parameter, with true indicating support. */
    @field:JsonProperty("request_parameter_supported")
    val requestParameterSupported: kotlin.Boolean? = null,
    /* Boolean value specifying whether the OP supports use of the request_uri parameter, with true indicating support. */
    @field:JsonProperty("request_uri_parameter_supported")
    val requestUriParameterSupported: kotlin.Boolean? = null,
    /* Boolean value specifying whether the OP requires any request_uri values used to be pre-registered using the request_uris registration parameter. */
    @field:JsonProperty("require_request_uri_registration")
    val requireRequestUriRegistration: kotlin.Boolean? = null,
    /* JSON array containing a list of the OAuth 2.0 response_mode values that this OP supports. */
    @field:JsonProperty("response_modes_supported")
    val responseModesSupported: kotlin.collections.List<kotlin.String>? = null,
    /* URL of the authorization server's OAuth 2.0 revocation endpoint. */
    @field:JsonProperty("revocation_endpoint")
    val revocationEndpoint: kotlin.String? = null,
    /* SON array containing a list of the OAuth 2.0 [RFC6749] scope values that this server supports. The server MUST support the openid scope value. Servers MAY choose not to advertise some supported scope values even when this parameter is used */
    @field:JsonProperty("scopes_supported")
    val scopesSupported: kotlin.collections.List<kotlin.String>? = null,
    /* JSON array containing a list of Client Authentication methods supported by this Token Endpoint. The options are client_secret_post, client_secret_basic, client_secret_jwt, and private_key_jwt, as described in Section 9 of OpenID Connect Core 1.0 */
    @field:JsonProperty("token_endpoint_auth_methods_supported")
    val tokenEndpointAuthMethodsSupported: kotlin.collections.List<kotlin.String>? = null,
    /* URL of the OP's UserInfo Endpoint. */
    @field:JsonProperty("userinfo_endpoint")
    val userinfoEndpoint: kotlin.String? = null,
    /* JSON array containing a list of the JWS [JWS] signing algorithms (alg values) [JWA] supported by the UserInfo Endpoint to encode the Claims in a JWT [JWT]. */
    @field:JsonProperty("userinfo_signing_alg_values_supported")
    val userinfoSigningAlgValuesSupported: kotlin.collections.List<kotlin.String>? = null
)
